#! /usr/bin/perl

# Copyright (c) 2014 DeNA Co., Ltd.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

use strict;
use warnings;
use Text::MicroTemplate qw(build_mt);

sub build_d {
    return build_mt(template => << 'EOT', escape_func => undef)->(@_);
? my ($type, $suffix, $min, $max) = @_;
static inline int _qrintf_nck_<?= $suffix ?>_core(char *buf, <?= $type ?> v)
{
    int i = 0;
    if (v < 0) {
        if (v == <?= $min ?>) {
            buf[i++] = '1' + <?= $max ?> % 10;
            v = <?= $max ?> / 10;
        } else {
            v = -v;
        }
    }
    do {
        buf[i++] = '0' + v % 10;
    } while ((v /= 10) != 0);
    return i;
}

static inline qrintf_nck_t _qrintf_nck_<?= $suffix ?>(qrintf_nck_t ctx, <?= $type ?> v)
{
    char buf[sizeof(<?= $type ?>) * 3];
    int len;
    if (v < 0)
        ctx.str[ctx.off++] = '-';
    len = _qrintf_nck_<?= $suffix ?>_core(buf, v);
    do {
        ctx.str[ctx.off++] = buf[--len];
    } while (len != 0);
    return ctx;
}

static inline qrintf_nck_t _qrintf_nck_width_<?= $suffix ?>(qrintf_nck_t ctx, int fill_ch, int width, <?= $type ?> v)
{
    char buf[sizeof(<?= $type ?>) * 3 + 1];
    int len = _qrintf_nck_<?= $suffix ?>_core(buf, v);
    if (v < 0) {
        if (fill_ch == ' ') {
            buf[len++] = '-';
        } else {
            ctx.str[ctx.off++] = '-';
            --width;
        }
    }
    for (; len < width; --width)
        ctx.str[ctx.off++] = fill_ch;
    do {
        ctx.str[ctx.off++] = buf[--len];
    } while (len != 0);
    return ctx;
}
EOT
}

sub build_u {
    my ($type, $suffix, $max, $with_width) = @_;
    return build_mt(template => << 'EOT', escape_func => undef)->($type, $suffix, $max, $with_width ? '_width' : '');
? my ($type, $suffix, $max, $width) = @_;
static inline qrintf_nck_t _qrintf_nck<?= $width ?>_<?= $suffix ?>(qrintf_nck_t ctx<?= $width ? ", int fill_ch, int width" : "" ?>, <?= $type ?> v)
{
    char tmp[sizeof(<?= $type ?>) * 3];
    int len = 0;
    do {
        tmp[len++] = '0' + v % 10;
    } while ((v /= 10) != 0);
? if ($width) {
    for (; len < width; --width)
        ctx.str[ctx.off++] = fill_ch;
? }
    do {
        ctx.str[ctx.off++] = tmp[--len];
    } while (len != 0);
    return ctx;
}
EOT
}

sub build_x {
    my ($type, $suffix, $with_width) = @_;
    return build_mt(template => << 'EOT', escape_func => undef)->($type, $suffix, $with_width ? '_width' : '');
? my ($type, $suffix, $width) = @_;
static inline qrintf_nck_t _qrintf_nck<?= $width ?>_<?= $suffix ?>(qrintf_nck_t ctx<?= $width ? ", int fill_ch, int width" : "" ?>, <?= $type ?> v)
{
    int len;
    if (v != 0) {
        int bits;
        if (sizeof(<?= $type ?>) == sizeof(unsigned long long))
            bits = sizeof(unsigned long long) * 8 - __builtin_clzll(v);
        else if (sizeof(<?= $type ?>) == sizeof(unsigned long))
            bits = sizeof(unsigned long) * 8 - __builtin_clzl(v);
        else
            bits = sizeof(int) * 8 - __builtin_clz(v);
        len = (bits + 3) >> 2;
    } else {
        len = 1;
    }
? if ($width) {
    for (; len < width; --width)
        ctx.str[ctx.off++] = fill_ch;
? }
    len *= 4;
    do {
        len -= 4;
        ctx.str[ctx.off++] = (<?= $suffix =~ /X$/ ? '"0123456789ABCDEF"' : '"0123456789abcdef"' ?>)[(v >> len) & 0xf];
    } while (len != 0);
    return ctx;
}
EOT
}

open my $fh, '>', 'share/qrintf/qrintf.h'
    or die "failed to open share/qrintf/qrintf.h:$!";

print $fh build_mt(template => << 'EOT', escape_func => undef)->(\&build_d, \&build_u, \&build_x)->as_string;
? my ($build_d, $build_u, $build_x) = @_;
/* DO NOT EDIT!  Automatically generated by misc/gen-printf.h.pl */
/*
 * Copyright (c) 2014 DeNA Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
#ifndef qrintf_h
#define qrintf_h

#ifdef __cplusplus
extern "C" {
#endif

#include <limits.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#undef sprintf
#define sprintf _qp_sprintf

#if _QRINTF_COUNT_CALL
extern size_t _qrintf_call_cnt;
#endif

typedef struct qrintf_nck_t {
  char *str;
  size_t off;
} qrintf_nck_t;

static inline qrintf_nck_t _qrintf_nck_init(char *str)
{
    struct qrintf_nck_t ret;
    ret.str = str;
    ret.off = 0;
#if _QRINTF_COUNT_CALL
    ++_qrintf_call_cnt;
#endif
    return ret;
}

static inline int _qrintf_nck_finalize(qrintf_nck_t ctx)
{
    ctx.str[ctx.off] = '\0';
    return (int)ctx.off;
}

static inline qrintf_nck_t _qrintf_nck_c(qrintf_nck_t ctx, int c)
{
    ctx.str[ctx.off++] = c;
    return ctx;
}

static inline qrintf_nck_t _qrintf_nck_width_c(qrintf_nck_t ctx, int fill_ch, int width, int c)
{
    for (; 1 < width; --width)
        ctx.str[ctx.off++] = fill_ch;
    ctx.str[ctx.off++] = c;
    return ctx;
}

static inline qrintf_nck_t _qrintf_nck_s(qrintf_nck_t ctx, const char *s)
{
    for (; *s != '\0'; ++s)
        ctx.str[ctx.off++] = *s;
    return ctx;
}

static inline qrintf_nck_t _qrintf_nck_width_s(qrintf_nck_t ctx, int fill_ch, int width, const char *s)
{
    int slen = strlen(s);
    for (; slen < width; --width)
        ctx.str[ctx.off++] = fill_ch;
    for (; slen != 0; --slen)
        ctx.str[ctx.off++] = *s++;
    return ctx;
}

static inline qrintf_nck_t _qrintf_nck_s_len(qrintf_nck_t ctx, const char *s, size_t l)
{
    for (; l != 0; --l)
        ctx.str[ctx.off++] = *s++;
    return ctx;
}

<?= $build_d->("short", "hd", "SHRT_MIN", "SHRT_MAX") ?>
<?= $build_d->("int", "d", "INT_MIN", "INT_MAX") ?>
<?= $build_d->("long", "ld", "LONG_MIN", "LONG_MAX") ?>
<?= $build_d->("long long", "lld", "LLONG_MIN", "LLONG_MAX") ?>
? for my $with_width (0..1) {
<?= $build_u->("unsigned short", "hu", "USHRT_MAX", $with_width) ?>
<?= $build_u->("unsigned", "u", "UINT_MAX", $with_width) ?>
<?= $build_u->("unsigned long", "lu", "ULONG_MAX", $with_width) ?>
<?= $build_u->("unsigned long long", "llu", "ULLONG_MAX", $with_width) ?>
<?= $build_u->("size_t", "zu", "SIZE_MAX", $with_width) ?>
? }

? for my $suffix (qw(x X)) {
?   for my $with_width (0..1) {
<?= $build_x->("unsigned short", "h$suffix", $with_width) ?>
<?= $build_x->("unsigned", "$suffix", $with_width) ?>
<?= $build_x->("unsigned long", "l$suffix", $with_width) ?>
<?= $build_x->("unsigned long long", "ll$suffix", $with_width) ?>
<?= $build_x->("size_t", "z$suffix", $with_width) ?>
?   }
? }

#ifdef __cplusplus
}
#endif

#endif
EOT
close $fh;
