#! /usr/bin/perl

# Copyright (c) 2014 DeNA Co., Ltd.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

use strict;
use warnings;
use Text::MicroTemplate qw(build_mt);

sub build_d {
    return build_mt(template => << 'EOT', escape_func => undef)->(@_);
? my ($check, $type, $suffix, $min, $max) = @_;
static inline qrintf_<?= $check ?>_t _qrintf_<?= $check ?>_<?= $suffix ?>(qrintf_<?= $check ?>_t ctx, <?= $type ?> v)
{
    unsigned long long val = v;
    int sign = v < 0;
    if (v < 0) {
        if (v == <?= $min ?>) {
            val = (unsigned long long)(<?= $max ?>) + 1;
        } else {
            val = (unsigned long long)(-v);
        }
    }
    return _qrintf_<?= $check ?>_int_core(ctx, 0, 0, val, sign);
}

static inline qrintf_<?= $check ?>_t _qrintf_<?= $check ?>_width_<?= $suffix ?>(qrintf_<?= $check ?>_t ctx, int fill_ch, int width, <?= $type ?> v)
{
    unsigned long long val = v;
    int sign = v < 0;
    if (v < 0) {
        if (v == <?= $min ?>) {
            val = (unsigned long long)(<?= $max ?>) + 1;
        } else {
            val = (unsigned long long)(-v);
        }
    }
    return _qrintf_<?= $check ?>_int_core(ctx, fill_ch, width, val, sign);
}
EOT
}

sub build_u {
    my ($check, $type, $suffix, $max) = @_;
    return build_mt(template => << 'EOT', escape_func => undef)->($check, $type, $suffix, $max);
? my ($check, $type, $suffix, $max) = @_;

static inline qrintf_<?= $check ?>_t _qrintf_<?= $check ?>_<?= $suffix ?>(qrintf_<?= $check ?>_t ctx, <?= $type ?> v)
{
    return _qrintf_<?= $check ?>_int_core(ctx, 0, 0, (unsigned long long)v, 0);
}

static inline qrintf_<?= $check ?>_t _qrintf_<?= $check ?>_width_<?= $suffix ?>(qrintf_<?= $check ?>_t ctx, int fill_ch, int width, <?= $type ?> v)
{
    return _qrintf_<?= $check ?>_int_core(ctx, fill_ch, width, (unsigned long long)v, 0);
}
EOT
}

sub build_x {
    my ($check, $type, $suffix, $with_width) = @_;
    return build_mt(template => << 'EOT', escape_func => undef)->($check, $type, $suffix, $with_width ? '_width' : '');
? my ($check, $type, $suffix, $width) = @_;
? my $push = $check eq 'chk' ? sub { "do { int ch = $_[0]; if (ctx.off < ctx.size) ctx.str[ctx.off] = ch; ++ctx.off; } while (0)" } : sub { "ctx.str[ctx.off++] = $_[0]" };
static inline qrintf_<?= $check ?>_t _qrintf_<?= $check ?><?= $width ?>_<?= $suffix ?>(qrintf_<?= $check ?>_t ctx<?= $width ? ", int fill_ch, int width" : "" ?>, <?= $type ?> v, const char *chars)
{
    int len;
    if (v != 0) {
        int bits;
        if (sizeof(<?= $type ?>) == sizeof(unsigned long long))
            bits = sizeof(unsigned long long) * 8 - __builtin_clzll(v);
        else if (sizeof(<?= $type ?>) == sizeof(unsigned long))
            bits = sizeof(unsigned long) * 8 - __builtin_clzl(v);
        else
            bits = sizeof(int) * 8 - __builtin_clz(v);
        len = (bits + 3) >> 2;
    } else {
        len = 1;
    }
? if ($width) {
    ctx = _qrintf_<?= $check ?>_fill(ctx, fill_ch, len, width);
? }
    len *= 4;
    do {
        len -= 4;
        <?= $push->(q{chars[(v >> len) & 0xf]}) ?>;
    } while (len != 0);
    return ctx;
}
EOT
}

open my $fh, '>', 'share/qrintf/qrintf.h'
    or die "failed to open share/qrintf/qrintf.h:$!";

print $fh build_mt(template => << 'EOT', escape_func => undef)->(\&build_d, \&build_u, \&build_x)->as_string;
? my ($build_d, $build_u, $build_x) = @_;
/* DO NOT EDIT!  Automatically generated by misc/gen-printf.h.pl */
/*
 * Copyright (c) 2014 DeNA Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
#ifndef qrintf_h
#define qrintf_h

#ifdef __cplusplus
extern "C" {
#endif

#include <limits.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#undef sprintf
#define sprintf(...) _qp_sprintf(__VA_ARGS__)
#undef snprintf
#define snprintf(...) _qp_snprintf(__VA_ARGS__)

#if _QRINTF_COUNT_CALL
extern size_t _qrintf_call_cnt;
#endif

typedef struct qrintf_nck_t {
    char *str;
    size_t off;
} qrintf_nck_t;

typedef struct qrintf_chk_t {
    char *str;
    size_t off;
    size_t size;
} qrintf_chk_t;

static inline qrintf_nck_t _qrintf_nck_init(char *str)
{
    qrintf_nck_t ctx;
    ctx.str = str;
    ctx.off = 0;
#if _QRINTF_COUNT_CALL
    ++_qrintf_call_cnt;
#endif
    return ctx;
}

static inline qrintf_chk_t _qrintf_chk_init(char *str, size_t size)
{
    qrintf_chk_t ctx;
    ctx.str = str;
    ctx.off = 0;
    ctx.size = size;
#if _QRINTF_COUNT_CALL
    ++_qrintf_call_cnt;
#endif
    return ctx;
}

static inline int _qrintf_nck_finalize(qrintf_nck_t ctx)
{
    ctx.str[ctx.off] = '\0';
    return (int)ctx.off;
}

static inline int _qrintf_chk_finalize(qrintf_chk_t ctx)
{
    ctx.str[ctx.off < ctx.size ? ctx.off : ctx.size - 1] = '\0';
    return (int)ctx.off;
}

static inline qrintf_nck_t _qrintf_nck_s_len(qrintf_nck_t ctx, const char *s, size_t l)
{
    for (; l != 0; --l)
        ctx.str[ctx.off++] = *s++;
    return ctx;
}

static inline qrintf_chk_t _qrintf_chk_s_len(qrintf_chk_t ctx, const char *s, size_t l)
{
    size_t off = ctx.off;
    ctx.off += l;
    if (off + l <= ctx.size) {
    } else if (off < ctx.size) {
        l = ctx.size - off;
    } else {
        goto Exit;
    }
    for (; l != 0; --l)
        ctx.str[off++] = *s++;
Exit:
    return ctx;
}

static inline qrintf_nck_t _qrintf_nck_fill(qrintf_nck_t ctx, int ch, size_t len, int width)
{
    for (; len < width; --width)
        ctx.str[ctx.off++] = ch;
    return ctx;
}

static inline qrintf_chk_t _qrintf_chk_fill(qrintf_chk_t ctx, int ch, size_t len, int width)
{
    if (len < width) {
        size_t off = ctx.off, l = width - len;
        ctx.off += l;
        if (off + l <= ctx.size) {
        } else if (off < ctx.size) {
            l = ctx.size - off;
        } else {
            goto Exit;
        }
        for (; l != 0; --l)
            ctx.str[off++] = ch;
    }
Exit:
    return ctx;
}

static inline qrintf_nck_t _qrintf_nck_s(qrintf_nck_t ctx, const char *s)
{
    for (; *s != '\0'; ++s)
        ctx.str[ctx.off++] = *s;
    return ctx;
}

static inline qrintf_chk_t _qrintf_chk_s(qrintf_chk_t ctx, const char *s)
{
    return _qrintf_chk_s_len(ctx, s, strlen(s));
}

? for my $check (qw(nck chk)) {
?   my $push = $check eq 'chk' ? sub { "do { int ch = $_[0]; if (ctx.off < ctx.size) ctx.str[ctx.off] = ch; ++ctx.off; } while (0)" } : sub { "ctx.str[ctx.off++] = $_[0]" };
static inline qrintf_<?= $check ?>_t _qrintf_<?= $check ?>_c(qrintf_<?= $check ?>_t ctx, int c)
{
    <?= $push->(q{c}) ?>;
    return ctx;
}

static inline qrintf_<?= $check ?>_t _qrintf_<?= $check ?>_width_c(qrintf_<?= $check ?>_t ctx, int fill_ch, int width, int c)
{
    ctx = _qrintf_<?= $check ?>_fill(ctx, fill_ch, 1, width);
    <?= $push->(q{c}) ?>;
    return ctx;
}

static inline qrintf_<?= $check ?>_t _qrintf_<?= $check ?>_width_s(qrintf_<?= $check ?>_t ctx, int fill_ch, int width, const char *s)
{
    int slen = strlen(s);
    ctx = _qrintf_<?= $check ?>_fill(ctx, fill_ch, slen, width);
    return _qrintf_<?= $check ?>_s_len(ctx, s, slen);
}
? }

static inline const char *_qrintf_get_digit_table(void)
{
    static const char digits_table[] = {
        "00010203040506070809"
        "10111213141516171819"
        "20212223242526272829"
        "30313233343536373839"
        "40414243444546474849"
        "50515253545556575859"
        "60616263646566676869"
        "70717273747576777879"
        "80818283848586878889"
        "90919293949596979899"
    };
    return digits_table;
}

static inline unsigned ilog10ull(uint64_t v)
{
#define LOG2(N) ((unsigned)((sizeof(unsigned long long) * 8) - __builtin_clzll((N)-1)))
    /* from http://graphics.stanford.edu/~seander/bithacks.html#IntegerLog10 */
    static const unsigned long long ilog10table[] = {
        1ULL,
        10ULL,
        100ULL,
        1000ULL,
        10000ULL,
        100000ULL,
        1000000ULL,
        10000000ULL,
        100000000ULL,
        1000000000ULL,
        10000000000ULL,
        100000000000ULL,
        1000000000000ULL,
        10000000000000ULL,
        100000000000000ULL,
        1000000000000000ULL,
        10000000000000000ULL,
        100000000000000000ULL,
        1000000000000000000ULL,
        10000000000000000000ULL,
        ULLONG_MAX,
    };
    if (v != 0) {
        unsigned t;
        t = ((LOG2(v) + 1) * 1233) / 4096;
        return t + (v >= ilog10table[t]);
    }
    else {
        return 1;
    }
#undef LOG2
}

static inline void _qrintf_int_core(char *p, unsigned long long val)
{
    const char *digits = _qrintf_get_digit_table();
    while (val >= 100) {
        unsigned idx = val % 100 * 2;
        *p-- = digits[idx + 1];
        *p-- = digits[idx];
        val /= 100;
    }
    if (val < 10) {
        *p-- = '0' + val;
    } else {
        *p-- = digits[val * 2 + 1];
        *p-- = digits[val * 2];
    }
}

static inline qrintf_nck_t _qrintf_nck_int_core(qrintf_nck_t ctx, int fill_ch, int width, unsigned long long v, int sign)
{
    unsigned long long val = (unsigned long long) v;
    int len = ilog10ull(val);
    int wlen = len;
    if (fill_ch == ' ') {
        ctx = _qrintf_nck_fill(ctx, fill_ch, len + sign, width);
    }
    if (sign) {
        ctx.str[ctx.off++] = '-';
        width -= 1;
    }
    if (fill_ch == '0') {
        ctx = _qrintf_nck_fill(ctx, fill_ch, len, width);
    }

    _qrintf_int_core(ctx.str + ctx.off + wlen - 1, val);
    ctx.off += len;
    return ctx;
}

static inline qrintf_chk_t _qrintf_chk_int_core(qrintf_chk_t ctx, int fill_ch, int width, unsigned long long v, int sign)
{
    unsigned long long val = (unsigned long long) v;
    int len = ilog10ull(val);
    int wlen = len;
    if (ctx.off + wlen + sign > ctx.size) {
        int n = ctx.off + wlen + sign - ctx.size - 1;
        wlen -= n;
        while (n-- != 0) {
            val /= 10;
        }
    }
    if (fill_ch == ' ') {
        ctx = _qrintf_chk_fill(ctx, fill_ch, len + sign, width);
    }
    if (sign && ctx.off + 1 < ctx.size) {
        ctx.str[ctx.off++] = '-';
        width -= 1;
    }
    if (fill_ch == '0') {
        ctx = _qrintf_chk_fill(ctx, fill_ch, len, width);
    }

    _qrintf_int_core(ctx.str + ctx.off + wlen - 1, val);
    ctx.off += len;
    return ctx;
}

? for my $check (qw(nck chk)) {
<?= $build_d->($check, "short", "hd", "SHRT_MIN", "SHRT_MAX") ?>
<?= $build_d->($check, "int", "d", "INT_MIN", "INT_MAX") ?>
<?= $build_d->($check, "long", "ld", "LONG_MIN", "LONG_MAX") ?>
<?= $build_d->($check, "long long", "lld", "LLONG_MIN", "LLONG_MAX") ?>
<?= $build_u->($check, "unsigned short", "hu", "USHRT_MAX") ?>
<?= $build_u->($check, "unsigned", "u", "UINT_MAX") ?>
<?= $build_u->($check, "unsigned long", "lu", "ULONG_MAX") ?>
<?= $build_u->($check, "unsigned long long", "llu", "ULLONG_MAX") ?>
<?= $build_u->($check, "size_t", "zu", "SIZE_MAX") ?>
?   for my $with_width (0..1) {
<?= $build_x->($check, "unsigned short", "hx", $with_width) ?>
<?= $build_x->($check, "unsigned", "x", $with_width) ?>
<?= $build_x->($check, "unsigned long", "lx", $with_width) ?>
<?= $build_x->($check, "unsigned long long", "llx", $with_width) ?>
<?= $build_x->($check, "size_t", "zx", $with_width) ?>
?   }
? }

#ifdef __cplusplus
}
#endif

#endif
EOT
close $fh;
