#! /usr/bin/perl

# Copyright (c) 2014,2015 DeNA Co., Ltd., Kazuho Oku
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

use strict;
use warnings;
use File::Basename qw(dirname);
use POSIX qw(WIFEXITED WEXITSTATUS);

if (! grep { $_ eq '-E' } @ARGV) {
    exec @ARGV;
    die "failed to exec $ARGV[0]:$!";
}

my $pwd = dirname($0);

# invoke cpp
my ($cpp_cmd, @cpp_args) = @ARGV;
system($cpp_cmd, '-DQRINTF=1', '-include', "$pwd/../../include/qrintf.h", @cpp_args) == 0
    or exit($? >> 8 ? $? >> 8 : 1);

# read the source file
my $src_fn = $ARGV[$#ARGV];
my $src = do {
    open my $fh, '<', $src_fn;
    join '', <$fh>;
};

# filter and print
open my $fh, "| $^X $pwd/../../bin/qrintf-pp > $src_fn"
    or die "failed to invoke $pwd/qrintf-pp:$!";
print $fh $src;
close $fh
    or exit($? >> 8 ? $? >> 8 : 1);
