#! /usr/bin/perl

use strict;
use warnings;
use File::Basename qw(dirname);

if (! grep { $_ eq '-E' } @ARGV) {
    exec @ARGV;
    die "failed to exec $ARGV[0]:$!";
}

my $pwd = dirname($0);

# invoke cpp
my ($cpp_cmd, @cpp_args) = @ARGV;
system($cpp_cmd, '-DQRINTF=1', '-include', "$pwd/qrintf.h", @cpp_args) == 0
    or exit $?;

# read the source file
my $src_fn = $ARGV[$#ARGV];
my $src = do {
    open my $fh, '<', $src_fn;
    join '', <$fh>;
};

# filter and print
open my $fh, "| $pwd/qrintf-pp > $src_fn"
    or die "failed to invoke $pwd/qrintf-pp:$!";
print $fh $src;
close $fh;

exit $?;

